### ISSUE TITLE
[FeatureRequest] Text Search box in top right of navigation bar

### ISSUE THREAD

**Issue by takuya-takeuchi** [mrcore/hexo-theme-Anatole-Core#2]
Hi. thank you for your great product.
And I'm very sorry to raise issue by English.

Could you add text search box in top right of navigation bar?

![image](https://user-images.githubusercontent.com/6241854/90974784-4a5a9a80-e569-11ea-8cee-a7b2f3ab7117.png)

Thank you for your cooperations.

**Comment by mrcore** [comment]
@takuya-takeuchi   Sorry, I'm a bit busy lately.     I checked the information. I can use the hexo-generator-search plug-in to generate search.xml file for title search, but I can’t do a full text search. You can try.

**Comment by takuya-takeuchi** [comment]
@mrcore 
Ok, sure. Thank you for your kindly advice.
