### ISSUE TITLE
[Feature] 希望支持 <!-- more --> 特性

### ISSUE THREAD

**Issue by muzig1** [mrcore/hexo-theme-Anatole-Core#3]
首先, 大佬, 我很喜欢你设计的主题, 目前自己也在自学前端, 真的太棒了.
不过, 还希望大佬你能支持一些细节. 
首页在显示的文字支持使用  来, 只显示部分想显示的内容.

**Comment by mrcore** [comment]
你是说想自定义首页文章标题下的内容？

**Comment by muzig1** [comment]
![Snipaste_2020-08-27_13-43-33](https://user-images.githubusercontent.com/38173919/91395209-7168e300-e86d-11ea-999c-f393a5d531fa.png)
![Snipaste_2020-08-27_13-42-57](https://user-images.githubusercontent.com/38173919/91395441-804f9580-e86d-11ea-842c-72462c22992e.png)

大概就是  能够标识文章显示的内容; 不过突然在截图的时候发现, 好像大佬你设计的排版固定的, 所以突然觉得按照你设计的挺好的, 哈哈.
