### ISSUE TITLE
网站icon问题

### ISSUE THREAD

**Issue by HeilantG** [mrcore/hexo-theme-Anatole-Core#4]
在`_config.yml`设置`avatar`未生效
我查询了所有文件中的内容 发现并没有使用这个配置(或许是我没有找到
目测是因为 `/layout/partial/head.pug` 中没有引入,我增加了一行
`link(rel="icon", href= url_for('images/favicon.ico'),type="image/x-icon")`
但是我并不知怎么在这个地方去读取配置

**Comment by mrcore** [comment]
你不用修改配置，替换主题下source/images/favicon.ico就好了
